version: '3'
services:
  web:
    image: wyveo/nginx-php-fpm:php72
    container_name: piadmin
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 80:80
    restart: always
    networks:
      - app-network
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: piadmin_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  adminer:
    image: adminer
    container_name: piadmin_dminer
    restart: always
    ports:
      - 81:8080
    networks:
      - app-network
  redis:
    image: redis
    container_name: piadmin_cache
    expose:
      - 6379
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
